package drachenbauer32.angrybirdsmod.init;

import net.minecraft.block.Block;

public class AngryBirdsBlocks
{	
    public static Block balloon_block,
                        balloon_block_top,
                        egg_block,
                        nest_block,
                        slingshot_acacia_block,
                        slingshot_acacia_wood_base_block,
                        slingshot_acacia_2_block,
                        slingshot_acacia_2_wood_base_block,
                        slingshot_acacia_block_side,
                        slingshot_acacia_block_side_top,
                        slingshot_birch_block,
                        slingshot_birch_wood_base_block,
                        slingshot_birch_2_block,
                        slingshot_birch_2_wood_base_block,
                        slingshot_birch_block_side,
                        slingshot_birch_block_side_top,
                        slingshot_dark_oak_block,
                        slingshot_dark_oak_wood_base_block,
                        slingshot_dark_oak_2_block,
                        slingshot_dark_oak_2_wood_base_block,
                        slingshot_dark_oak_block_side,
                        slingshot_dark_oak_block_side_top,
                        slingshot_jungle_block,
                        slingshot_jungle_wood_base_block,
                        slingshot_jungle_2_block,
                        slingshot_jungle_2_wood_base_block,
                        slingshot_jungle_block_side,
                        slingshot_jungle_block_side_top,
                        slingshot_oak_block,
                        slingshot_oak_wood_base_block,
                        slingshot_oak_2_block,
                        slingshot_oak_2_wood_base_block,
                        slingshot_oak_block_side,
                        slingshot_oak_block_side_top,
                        slingshot_spruce_block,
                        slingshot_spruce_wood_base_block,
                        slingshot_spruce_2_block,
                        slingshot_spruce_2_wood_base_block,
                        slingshot_spruce_block_side,
                        slingshot_spruce_block_side_top,
                        acacia_planks_frame_block,
                        birch_planks_frame_block,
                        dark_oak_planks_frame_block,
                        jungle_planks_frame_block,
                        oak_planks_frame_block,
                        spruce_planks_frame_block,
                        stone_frame_block,
                        blue_ice_frame_block;
}