package drachenbauer32.angrybirdsmod.init;

import net.minecraft.block.Block;

public class AngryBirdsBlocks
{	
    public static Block egg_block,
                        nest,
                        
                        slingshot_acacia,
                        slingshot_acacia_wood_base,
                        slingshot_acacia_2,
                        slingshot_acacia_2_wood_base,
                        slingshot_acacia_side,
                        slingshot_acacia_side_top,
                        
                        slingshot_birch,
                        slingshot_birch_wood_base,
                        slingshot_birch_2,
                        slingshot_birch_2_wood_base,
                        slingshot_birch_side,
                        slingshot_birch_side_top,
                        
                        slingshot_dark_oak,
                        slingshot_dark_oak_wood_base,
                        slingshot_dark_oak_2,
                        slingshot_dark_oak_2_wood_base,
                        slingshot_dark_oak_side,
                        slingshot_dark_oak_side_top,
                        
                        slingshot_jungle,
                        slingshot_jungle_wood_base,
                        slingshot_jungle_2,
                        slingshot_jungle_2_wood_base,
                        slingshot_jungle_side,
                        slingshot_jungle_side_top,
                        
                        slingshot_oak,
                        slingshot_oak_wood_base,
                        slingshot_oak_2,
                        slingshot_oak_2_wood_base,
                        slingshot_oak_side,
                        slingshot_oak_side_top,
                        
                        slingshot_spruce,
                        slingshot_spruce_wood_base,
                        slingshot_spruce_2,
                        slingshot_spruce_2_wood_base,
                        slingshot_spruce_side,
                        slingshot_spruce_side_top,
                        
                        acacia_planks_frame,
                        birch_planks_frame,
                        dark_oak_planks_frame,
                        jungle_planks_frame,
                        oak_planks_frame,
                        spruce_planks_frame,
                        stone_frame,
                        blue_ice_frame,
                        
                        black_balloon,
                        blue_balloon,
                        brown_balloon,
                        cyan_balloon,
                        gray_balloon,
                        green_balloon,
                        light_blue_balloon,
                        light_gray_balloon,
                        lime_balloon,
                        magenta_balloon,
                        orange_balloon,
                        pink_balloon,
                        purple_balloon,
                        red_balloon,
                        white_balloon,
                        yellow_balloon,
                        
                        black_balloon_top,
                        blue_balloon_top,
                        brown_balloon_top,
                        cyan_balloon_top,
                        gray_balloon_top,
                        green_balloon_top,
                        light_blue_balloon_top,
                        light_gray_balloon_top,
                        lime_balloon_top,
                        magenta_balloon_top,
                        orange_balloon_top,
                        pink_balloon_top,
                        purple_balloon_top,
                        red_balloon_top,
                        white_balloon_top,
                        yellow_balloon_top;
}